#!/bin/bash

SCRIPT_DIR=$( dirname -- "$( realpath "$0"; )"; )
ZIP_DIR=$( realpath "$1"; )
ZIP_DIR_NAME=$( basename "$ZIP_DIR"; )

if ! [ -n "$ZIP_DIR" ]; then
     echo "usage: cosmologist [directory containing main.lua]" >&2
     exit 2
fi

mkdir -p "$ZIP_DIR/bin"

cd "$SCRIPT_DIR"

OUTPUT_NAME="$ZIP_DIR_NAME" BIN_DIR="$ZIP_DIR/bin" ZIP_EXTRAS_DIR="$ZIP_DIR" make

